### ISSUE TITLE
vendor/sony/yoshino-common/yoshino-partial.mk is being called, but is missing when choosing option 35 in the lunch menu

### ISSUE THREAD

**Issue by Umeaboy** [sonyxperiadev/device-sony-maple#10]
I have synced everything just perfectly and as I type lunch followed by choosing 35 I get this error:

build/core/product_config.mk:243: *** _nic.PRODUCTS.[[device/sony/maple/aosp_g8141.mk]]: "vendor/sony/yoshino-common/yoshino-partial.mk" does not exist.  Stoping.

This prevents Oreo from being built.

**Comment by jerpelea** [comment]
you forgot to add the vendor zip

**Comment by Umeaboy** [comment]
Which one and where can I find it?

**Comment by jerpelea** [comment]
https://developer.sonymobile.com/open-devices/list-of-devices-and-resources/

**Comment by Umeaboy** [comment]
After doing so I get this result:

[umeaboy@localhost ~]$ cd android/
[umeaboy@localhost android]$ source build/envsetup.sh
including device/asus/fugu/vendorsetup.sh
including device/generic/car/car-arm64/vendorsetup.sh
including device/generic/car/car-armv7-a-neon/vendorsetup.sh
including device/generic/car/car-x86_64/vendorsetup.sh
including device/generic/car/car-x86/vendorsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/generic/mini-emulator-mips64/vendorsetup.sh
including device/generic/mini-emulator-mips/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/google/dragon/vendorsetup.sh
including device/google/marlin/vendorsetup.sh
including device/huawei/angler/vendorsetup.sh
including device/lge/bullhead/vendorsetup.sh
including device/linaro/hikey/vendorsetup.sh
including device/sony/dora/vendorsetup.sh
including device/sony/kagura/vendorsetup.sh
including device/sony/keyaki/vendorsetup.sh
including device/sony/kugo/vendorsetup.sh
including device/sony/maple/vendorsetup.sh
including device/sony/suzu/vendorsetup.sh
including device/sony/tulip/vendorsetup.sh
including sdk/bash_completion/adb.bash
[umeaboy@localhost android]$ lunch

You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_mips-eng
     4. aosp_mips64-eng
     5. aosp_x86-eng
     6. aosp_x86_64-eng
     7. full_fugu-userdebug
     8. aosp_fugu-userdebug
     9. car_emu_arm64-userdebug
     10. car_emu_arm-userdebug
     11. car_emu_x86_64-userdebug
     12. car_emu_x86-userdebug
     13. mini_emulator_arm64-userdebug
     14. m_e_arm-userdebug
     15. m_e_mips64-eng
     16. m_e_mips-userdebug
     17. mini_emulator_x86_64-userdebug
     18. mini_emulator_x86-userdebug
     19. aosp_dragon-userdebug
     20. aosp_dragon-eng
     21. aosp_marlin-userdebug
     22. aosp_marlin_svelte-userdebug
     23. aosp_sailfish-userdebug
     24. aosp_angler-userdebug
     25. aosp_bullhead-userdebug
     26. aosp_bullhead_svelte-userdebug
     27. hikey-userdebug
     28. aosp_f8131-userdebug
     29. aosp_f8132-userdebug
     30. aosp_f8331-userdebug
     31. aosp_f8332-userdebug
     32. aosp_g8231-userdebug
     33. aosp_g8232-userdebug
     34. aosp_f5321-userdebug
     35. aosp_g8141-userdebug
     36. aosp_g8142-userdebug
     37. aosp_f5121-userdebug
     38. aosp_f5122-userdebug
     39. aosp_e2303-userdebug
     40. aosp_e2333-userdebug

Which would you like? [aosp_arm-eng] 35

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.0.0
TARGET_PRODUCT=aosp_g8141
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_PLATFORM_VERSION=OPR1
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a9
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.9.43-desktop-1.mga6-x86_64-with-mageia-6-Official
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPR6.170623.013
OUT_DIR=out
AUX_OS_VARIANT_LIST=
============================================
[umeaboy@localhost android]$ make -j4
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.0.0
TARGET_PRODUCT=aosp_g8141
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a9
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.9.43-desktop-1.mga6-x86_64-with-mageia-6-Official
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPR6.170623.013
OUT_DIR=out
============================================
[38/38] bootstrap out/soong/.minibootstrap/build.ninja.in
[4/4] cp out/soong/.bootstrap/bin/bpglob
[621/622] glob vendor/*/*/Android.bp
[40/40] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-aosp_g8141.ninja is missing, regenerating...
Checking build tools versions...
[9/986] including ./cts/Android.mk ...
cts/apps/CtsVerifier/Android.mk:72: warning: FindEmulator: find: `cts/apps/CtsVerifier/src/com/android/cts/verifier/backup': No such file or directory
build/core/java_common.mk:88: warning: FindEmulator: cd: cts/hostsidetests/appsecurity/test-apps/WriteExternalStorageApp/cts/hostsidetests/appsecurity/test-apps/WriteExternalStorageApp/res: No such file or directory
build/core/java_common.mk:88: warning: FindEmulator: cd: cts/hostsidetests/backup/assets: No such file or directory
cts/hostsidetests/os/test-apps/StaticSharedNativeLibProvider/Android.mk:23: warning: FindEmulator: find: `cts/hostsidetests/os/test-apps/StaticSharedNativeLibProvider/src': No such file or directory
cts/hostsidetests/os/test-apps/StaticSharedNativeLibProvider1/Android.mk:23: warning: FindEmulator: find: `cts/hostsidetests/os/test-apps/StaticSharedNativeLibProvider1/src': No such file or directory
cts/tests/tests/contactsproviderwipe/Android.mk:33: warning: FindEmulator: find: `cts/tests/tests/contactsproviderwipe/common/src': No such file or directory
cts/tests/tests/telecom3/Android.mk:37: warning: FindEmulator: find: `cts/tests/tests/telecom/src/android/telecom/cts/MockDialerActivity.java': No such file or directory
[147/986] including ./device/sony/common/Android.mk ...
device-sony-common-init: init_sony for "maple", platform "yoshino", with ' -DFOTA_RAMDISK_CHECK="0" -DKEYCHECK_ENABLED="1" -DKEYCHECK_NO_DOWN="1" -DDEV_BLOCK_PATH="\"/dev/block/sde"\" -DDEV_BLOCK_FOTA_PATH="\"/dev/block/sde45"\" -DDEV_BLOCK_FOTA_NUM="45" -DDEV_BLOCK_FOTA_MAJOR="259" -DDEV_BLOCK_FOTA_MINOR="29"'
[368/986] including ./frameworks/av/media/libaaudio/Android.mk ...
frameworks/av/media/libaaudio/examples/input_monitor/static/Android.mk: warning: input_monitor: unusual tags examples 
frameworks/av/media/libaaudio/examples/write_sine/static/Android.mk: warning: write_sine: unusual tags examples 
[402/986] including ./frameworks/base/Android.mk ...
./frameworks/base/Android.mk:865: warning: FindEmulator: find: `frameworks/opt/telephony/src/java/android/provider': No such file or directory
./frameworks/base/Android.mk:874: warning: FindEmulator: find: `frameworks/opt/telephony/src/java/android/provider': No such file or directory
./frameworks/base/Android.mk:879: warning: FindEmulator: find: `frameworks/opt/telephony/src/java/android/provider': No such file or directory
./frameworks/base/Android.mk:884: warning: FindEmulator: find: `frameworks/opt/telephony/src/java/android/provider': No such file or directory
[529/986] including ./hardware/qcom/gps/Android.mk ...
build/core/base_rules.mk:238: error: hardware/qcom/gps/msm8998/core: MODULE.TARGET.SHARED_LIBRARIES.libloc_core already defined by hardware/qcom/gps/msm8994/core.
00:44:36 ckati failed with: exit status 1
build/core/main.mk:21: receipt for target ”run_soong_ui” failed
make: *** [run_soong_ui] Error 1

#### make failed to build some targets (54 seconds) ####

**Comment by Umeaboy** [comment]
Had to delete the directory called msm8994 in /hardware/qcom/gps/ to get on with the build. However I see loads of warnings about missing files.

**Comment by jerpelea** [comment]
in your repository / there is a script called repo_update 
please run it and it will fix the build

we will update the build guide ASAP to include the new script

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues
