### ISSUE TITLE
cannot flash vendor partition

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/device-sony-maple#21]
As of 4 Oct, the AOSP build instructions for the Xerpia XZP state that its vendor partition should be flashed with the image provided here:

https://developer.sonymobile.com/downloads/software-binaries/software-binaries-for-aosp-nougat-android-7-1-kernel-4-4-yoshino/

Unfortunately, I am not able to flash the vendor partition on my XZP:

```
$ fastboot flash oem SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v03_yoshino.img
target reported max download size of 536870912 bytes
sending 'oem' (203753 KB)...
OKAY [  5.025s]
writing 'oem'...
FAILED (remote: Flashing is not allowed for partition
)
finished. total time: 5.026s
```

Any idea why I am not allowed to flash the vendor partition?

**Comment by jerpelea** [comment]
please update yoir device using our flashtool then flash the oem partition

**Comment by jamuir** [comment]
Thanks for your prompt reply, Alin.

I just flashed my device using the Emma flashtool.

Unfortunately, I hit the same error after I rebooted and tried to flash the vendor partition.

```
$ fastboot getvar all
(bootloader) unlocked:yes
(bootloader) off-mode-charge:0
(bootloader) charger-screen-enabled:0
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4273
(bootloader) version-baseband:1306-8501_45.0.A.5.1
(bootloader) version-bootloader:1306-5035_X_Boot_MSM8998_LA1.1_N_59-D
(bootloader) variant:MSM UFS
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache: 0x17C00000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0xCB5AF2000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system: 0x1CB600000
(bootloader) secure:no
(bootloader) serial:eef517cb
(bootloader) product:G8142
(bootloader) serialno:CB512EHFPJ
(bootloader) max-download-size:536870912
(bootloader) kernel:uefi
all: 
finished. total time: 0.001s

$ fastboot flash oem SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v03_yoshino.img
target reported max download size of 536870912 bytes
sending 'oem' (203753 KB)...
OKAY [  5.060s]
writing 'oem'...
FAILED (remote: Flashing is not allowed for partition
)
finished. total time: 5.060s
```

**Comment by jerpelea** [comment]
pladr update to the latest version
we have released a new one 35.0.A.7.137 if i remember correctly

**Comment by jamuir** [comment]
Unfortunately, "Emma" only offers me one device image,  `G8142 45.0.A.5.1`, and that is the one I have already installed.

Is there another way to download and flash the newest image?

**Comment by jerpelea** [comment]
we will check it tomorrow

**Comment by jamuir** [comment]
:+1:

**Comment by jerpelea** [comment]
mt coleagye will try to fix it Monday since there are some issues

**Comment by jamuir** [comment]
ok, thanks.

In the meantime, I'd like to go back to to building an XZP image where vendor components reside in the system partition (i.e. by using the v02 zip archive for vendor/sony/yoshino-common/).

Could you tell me what revision of device-sony-common I should reset to so I can do a build like that?

**Comment by jerpelea** [comment]
i dont recommand thay

**Comment by jerpelea** [comment]
I am looking what release will match best for you.
Where are you located?
Regards
Alin

**Comment by jamuir** [comment]
Canada.

btw, I realized I could flash the oem partition using `dd`.  I see that this was also suggested on the Sony Open Devices forum.  I wish I had seen that suggestion last week :-)

I now have a usable image and am no longer blocked waiting for the updated bootloader.

**Comment by jamuir** [comment]
@jerpelea :  any update on when the new image & bootloader be published?

**Comment by jerpelea** [comment]
flashtool has been updated 
please update your device

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues

**Comment by JamesOuver** [comment]
target reported max download size of 536870912 bytes
sending 'oem' (222444 KB)...
OKAY [457.634s]
writing 'oem'...
FAILED (remote: Flashing is not allowed in Lock State)
finished. total time: 457.638s
-----------------------------------------------------------------------
it is still there when i flash vendor image

**Comment by jerpelea** [comment]
to be able to flash the oem partition you must:
unlock your device using the unlock service
updae your device with the latest sony software( using flastool)
all services are privided on our new webpage
https://developer.sony.com
