### ISSUE TITLE
adaptive brightness makes screen too dim

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/device-sony-maple#22]
In builds created from the "n-mr1" branch (revision 1235ae9), adaptive brightness does not seem to be working correctly.

When the device starts up, adaptive brightness is enabled (as per the overlay in device/sony/common) but the screen is too dim.

If you disable adaptive brightness in Settings, then the screen brightness goes to a normal level.

**Comment by jerpelea** [comment]
duplicate
https://github.com/sonyxperiadev/bug_tracker/issues/1
