### ISSUE TITLE
[maple] Back camera doesn't support 19MP photo resolution

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [sonyxperiadev/device-sony-maple#33]
AOSP ROM has no 5056x3792 (4:3, 19.17MP) resolution that stock ROM has.

Other differences:

* AOSP ROM has non-standard (not 4:3 and not 16:9) 5504x3104 (172:97, 17.08MP) resolution. Is it instead of 5504x3096 (16:9, 17.04MP) resolution that stock ROM has, but AOSP ROM has not?
* AOSP ROM has no 4608x2592 (16:9, 11.94MP) resolution that stock ROM has.
* AOSP ROM has non-standard 3280x2464 (205:154, 8.08MP) resolution that stock ROM has not.
* AOSP ROM has 5312x2988 (16:9, 15.87MP) resolution that stock ROM has not.
* etc (compare screenshots):

AOSP:
![AOSP](https://user-images.githubusercontent.com/7892779/34721147-adffe932-f552-11e7-98cc-c16b3a88b651.png)

Stock:
![Stock](https://user-images.githubusercontent.com/7892779/34721150-b2360540-f552-11e7-90ae-8274178c0c5d.png)

**Comment by FluorescentHallucinogen** [comment]
@sonyxperiadev @jerpelea @kholk @alviteri @dutchdeveloper PTAL.

**Comment by FluorescentHallucinogen** [comment]
This issue may affect other devices, not only Sony XZ Premium (maple).

BTW, effective pixel count of IMX400 image sensor is 5520 (H) x 3840 (V) (23:16, 21.2 MP). Is it possible to enable resolution higher than 5056x3792 (4:3, 19.17MP)?

**Comment by YumeMichi** [comment]
DRM issue?

**Comment by FluorescentHallucinogen** [comment]
@YumeMichi 
> DRM issue?

No. As @jerpelea explained in https://github.com/sonyxperiadev/device-sony-lilac/issues/5, AOSP ROM does not use the DRM keys for camera functionality.

**Comment by jerpelea** [comment]
camera is set to 17Mp 16:9

**Comment by FluorescentHallucinogen** [comment]
@jerpelea
> camera is set to 17Mp 16:9

What do you mean? Could you please write exact resolution in pixels for 17Mp 16:9?

What camera API version you tested? Camera 2 API or Camera 1 API. List of available resolutions may vary depending on the camera API version.

Just checked in Open Camera app on Xperia XZ Premium (AOSP), I can succesfully shot only at 17MP maximum, but it is 172:97 (5504x3104), not 16:9.

**Comment by FluorescentHallucinogen** [comment]
@jerpelea Is it limited in binary blobs? Could you please enable (unlock) 19MP for AOSP?

**Comment by kholk** [comment]
First of all: it's not as easy as it sounds.

The 172:97 aspect ratio wanted to be 16:9, and it "sorta" is, internally... and we currently support the maximum resolution of 5504x3104 for IMX400, _without hacks_.

Btw, the situation surely needs to be carefully examined prior even being able to say "in the future" or "never".

**Comment by FluorescentHallucinogen** [comment]
@kholk 
> and we currently support the maximum resolution of 5504x3104 for IMX400, _without hacks_.

But what about 4:3 5056x3792 (19.17MP) resolution for IMX400, _without hacks_ (not 5504x3104)? Why it is not available?

**Comment by jerpelea** [comment]
current implementation uses 5504x3104 as max resolution

**Comment by JamesOuver** [comment]
fastboot flash oem SW_binaries_for_Xperia_AOSP_N_MR1_4.4_v05_yoshino.img

target reported max download size of 536870912 bytes
sending 'oem' (222444 KB)...
OKAY [457.634s]
writing 'oem'...
FAILED (remote: Flashing is not allowed in Lock State)
finished. total time: 457.638s

it is still there  fashing vendor 7.1(23.10.2017) on xzp

**Comment by JamesOuver** [comment]
cannot flash vendor img without EMMA?

**Comment by JamesOuver** [comment]
fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_v05_yoshino.img

target reported max download size of 536870912 bytes
sending 'oem' (218786 KB)...
OKAY [450.132s]
writing 'oem'...
FAILED (remote: Flashing is not allowed in Lock State)
finished. total time: 450.136s

it is still there fashing vendor 8.0(23.10.2017) on xzp

**Comment by jerpelea** [comment]
please note that we moved to a new domain https://developer.sony.com

**Comment by jerpelea** [comment]
for the moment there is no change for the camera resolution and when it will be we will comunicate it through the changelog

**Comment by FluorescentHallucinogen** [comment]
@jerpelea New binary blobs have been released for AOSP [8.0](https://developer.sony.com/file/download/software-binaries-for-aosp-oreo-android-8-0-kernel-4-4-yoshino/) (2018-01-12), [7.1](https://developer.sony.com/file/download/software-binaries-for-aosp-nougat-android-7-1-kernel-4-4-yoshino/) (2018-01-19), [8.1](https://developer.sony.com/file/download/software-binaries-for-aosp-oreo-android-8-1-kernel-4-4-yoshino/) (2018-01-26), but there's no word about change for the camera resolution in the changelogs. Is this issue fixed in any of these binary blobs?

**Comment by jerpelea** [comment]
as I stated in my previous comment if there will be a resolution change we will communicate it. 
this is not a bug!

**Comment by FluorescentHallucinogen** [comment]
@jerpelea Some "camera updates" are mentioned in the changelog for `sw_binaries_for_xperia_android_8.1.6.4_r1_v12_yoshino.zip`: https://developer.sony.com/develop/open-devices/latest-updates.

Is this issue finally fixed?

**Comment by jerpelea** [comment]
the camera is set to 19mp 4:3
which results in around 17mp 16:9

**Comment by FluorescentHallucinogen** [comment]
Why 5056x3792 can't be achieved on AOSP? Could you please explain the roots of this limitation?

**Comment by FluorescentHallucinogen** [comment]
BTW, I've also found that front (selfie) camera is also affected by this issue.

**Comment by FluorescentHallucinogen** [comment]
Any news on fixing this issue?

**Comment by jerpelea** [comment]
this is not and issue and will not be fixed
we have to use the 16:9 as the default camera mode to achieve higher FPS
