### ISSUE TITLE
/bin/bash: rad 0: pushd: out/target/product/maple/odm/: File or directory does not exist

### ISSUE THREAD

**Issue by CurveOS** [sonyxperiadev/device-sony-maple#44]
I was following the guide on how to build AOSP 8.1 and as I ran make -j4 I got the attached result:

[Build fails.log](https://github.com/sonyxperiadev/device-sony-maple/files/1951188/Build.fails.log)

**Comment by jamuir** [comment]
did you remember to apply the patches by running `./repo_update.sh` ?

**Comment by CurveOS** [comment]
I thought I did run it in my long line of command. However running ./repo_update.sh seems to fix that.
